version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8085:8080"  # Corrected port mapping for Jenkins
      - "50001:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client:ro

  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapp
    ports:
      - "5001:5000"  # Exposing Flask app port
    environment:
      - FLASK_ENV=development

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    container_name: git-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true
  git-data:
